version: "2"
services:
  consul:
    image: "progrium/consul:latest"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap-expect 1 -ui-dir /ui"
  gateway:
    build: .
    depends_on:
      - consul
    ports:
      - "8080:8080"
    command: "/gateway"
    restart: unless-stopped
  service-foo:
    build: .
    depends_on:
      - consul
    command: "/service -service foo"
    restart: unless-stopped
  service-bar:
    build: .
    depends_on:
      - consul
    command: "/service -service bar"
    restart: unless-stopped
